export const charmatrix = [
    ['M', 'E', 's', 'T', 'E', 'S', 'm', 'S', 'a', 'E', 'A', 'B', 'S', 'P', 'C'],
    ['o', 'C', 'p', 'i', 'M', 'R', 'R', 'e', 'l', 'N', 'E', 'E', 'A', 'A', 'a'],
    ['n', 'I', 'a', 'g', 'O', 'M', 'e', 'e', 'G', 'L', 'L', 'S', 'U', 'H', 'K'],
    ['k', 'R', 'c', 'e', 'C', 'f', 'p', 'R', 'I', 'R', 'T', 'S', 'A', 'R', 'z'],
    ['e', 'A', 'e', 'r', 'f', 'h', 'Y', 'N', 'A', 'L', 'T', 'B', 'E', 'O', 'g'],
    ['y', 'V', 'r', 'a', 'a', 'O', 'D', 'H', 'x', 'I', 'i', 'L', 'G', 'o', 'T'],
    ['r', 'A', 'r', 'n', 'L', 'A', 'C', 'O', 'C', 'a', 'C', 'o', 'r', 'O', 'P'],
    ['b', 'i', 't', 'D', 'u', 't', 'f', 'd', 'X', 'd', 'c', 'F', 'n', 'V', 'F'],
    ['G', 'E', 'L', 'L', 'E', 'B', 'a', 'a', 'r', 'n', 'B', 'c', 'B', 'E', 'D'],
    ['n', 'i', 'u', 'g', 'n', 'e', 'P', 'o', 't', 'a', 'k', 'r', 'e', 'e', 'M'],
    ['S', 'N', 'I', 'A', 'H', 'C', 'c', 'T', 'G', 'P', 'S', 'B', 'a', 'u', 'I'],
    ['A', 'l', 'l', 'i', 'g', 'a', 't', 'o', 'r', 'v', 'o', 't', 'O', 'e', 'T'],
    ['E', 'C', 'I', 'T', 'N', 'E', 'R', 'P', 'P', 'A', 'D', 's', 'o', 'B', 'B'],
    ['H', 'O', 'U', 'S', 'E', 'P', 'o', 'l', 'a', 'r', 'B', 'e', 'a', 'r', 'u'],
    ['N', 'W', 'O', 'G', 'C', 'R', 'A', 'T', 'C', 'H', 'I', 'T', 'E', 'Y', 'k']
]

export const words = [
    'Alligator',
    'ANGRY',
    'APPRENTICE',
    'AVARICE',
    'BAH',
    'Bear',
    'BED',
    'BELINDA',
    'BELLE',
    'BOB',
    'CAUSTIC',
    'CHAINS',
    'CHARLES',
    'CLERK',
    'COME',
    'CRATCHIT',
    'Elephant',
    'FOG',
    'Frog',
    'Giraffe',
    'Goat',
    'GOWN',
    'HOUSE',
    'Lion',
    'Meerkat',
    'Monkey',
    'MRS',
    'MRS',
    'OLD',
    'Panda',
    'PAST',
    'Penguin',
    'PolarBear',
    'spacer',
    'Stork',
    'Tiger',
    'TIM',
    'TO',
    'Toad',
    'YET'
]
