export const charmatrix = [
    ['d', 't', 'f', 'h', 'n', 'i', 'f', 'f', 'o', 'c', 'i', 'u', 'x', 'w', 'm'],
    ['m', 'o', 'h', 'w', 'f', 'n', 'f', 'q', 'h', 'y', 't', 'r', 'a', 'p', 'f'],
    ['a', 'm', 'a', 'm', 'i', 'a', 'a', 'w', 'h', 'f', 'c', 'j', 'v', 'k', 'j'],
    ['e', 'b', 'u', 'b', 'w', 't', 'd', 'r', 'a', 'y', 'e', 'v', 'a', 'r', 'g'],
    ['r', 'o', 'n', 'x', 'a', 'y', 'c', 'a', 'n', 'd', 'y', 'w', 'j', 'n', 'r'],
    ['c', 's', 't', 'r', 'r', 't', 'v', 'h', 'j', 'n', 'v', 'q', 'y', 'd', 't'],
    ['s', 'w', 'e', 'f', 'r', 'a', 'n', 'k', 'e', 'n', 's', 't', 'e', 'i', 'n'],
    ['p', 'c', 'd', 'w', 'e', 'm', 'u', 't', 's', 'o', 'c', 'e', 'i', 't', 'b'],
    ['o', 'a', 't', 'i', 'e', 'f', 'e', 'y', 'v', 'n', 'h', 'v', 'r', 'e', 'o'],
    ['o', 'u', 'h', 'a', 'c', 'r', 'r', 'x', 'm', 'b', 'w', 'i', 'e', 'r', 'o'],
    ['k', 'l', 'f', 'v', 'e', 'f', 'e', 'p', 'p', 'm', 'c', 'n', 't', 'i', 't'],
    ['y', 'd', 'z', 'c', 'c', 'r', 'x', 'w', 'k', 'k', 'u', 'm', 's', 'p', 's'],
    ['y', 'z', 'j', 'p', 'a', 's', 't', 'w', 'o', 'q', 'y', 'm', 'n', 'm', 'o'],
    ['a', 'o', 's', 'x', 't', 'n', 'o', 'o', 'm', 'l', 'h', 'e', 'o', 'a', 'h'],
    ['v', 'n', 'n', 'o', 't', 'e', 'l', 'e', 'k', 's', 'f', 'u', 'm', 'v', 'g']
]

export const words = [
    'ant',
    'azz',
    'bat',
    'boo',
    'candy',
    'cat',
    'cauldron',
    'coffin',
    'costume',
    'Frankenstein',
    'ghost',
    'graveyard',
    'haunted',
    'monster',
    'moon',
    'mummy',
    'party',
    'scream',
    'skeleton',
    'spooky',
    'tomb',
    'treat',
    'trick',
    'vampire',
    'werewolf',
    'witch'
]
